### ISSUE TITLE
Rewrite Jokolay Again

### ISSUE THREAD

**Issue by coderedart** [coderedart/jokolay#40]
### Windowing
Winit on web. Glfw on Desktop. 

### GUI
egui

### Rendering
There's only two 3D renderers in rust at the moment. `rend3` and `three-d`. but `rend3` cannot work on web unless webgpu is on stable (and it is very much not stable right now. neither chrome nor firefox on linux can render wgpu samples properly except the very basic ones). webgpu could be in chrome in february 2023.

so, if three-d gets a wgpu backend, then we an use that right now. lets try contributing for now. 
fortunately, for the forseeable future, we can easily work with just wgpu as we will only render egui + basic markers / trails (which are custom rendering anyway).

**Comment by coderedart** [comment]
trying to port `three_d` to wgpu failed. its way too hard and it feels like the performance would not be ideal with the existing immediate mode api.

wgpu uses the "command" style api of vulkan where it collects everything into a command buffer and then it just submits it to a queue. meanwhile `three_d` uses opengl style api where you just do interact with gpu live and make the driver deal with the asynchronous nature of GPUs.  

for now, we will just make a a wgpu renderer called Jokorender which will take care of egui and markers.

**Comment by royalmustard** [comment]
Why exactly would an overlay for a game that only runs on Desktop need to be running on web?

**Comment by coderedart** [comment]
Basically, everytime you add a feature to jokolay which doesn't need live mumble link data from game, you will need to duplicate it on web. 

gw2efficiency or gw2crafts.net or gw2skills.net or gw2bltc.com are all tools which are useful locally inside a game and on web. 

eventually, jokolay can also connect between user instances for some useful features. one example is a whole squad creating a marker pack -> like spreading out on a map and marking **all the** platinum ore nodes within a couple minutes. now, they can share this online and anyone that wants to farm platinum, can just follow that marker pack.

or roleplay. copy-pasting from another issue
> Jokolay was imagined as a linux native port (cross platform technically) of Taco, primarily intended to be used by RolePlayers to create custom "Quests" and other players being able to "play" them.

> We intended to use MumbleLink + Gw2 Api + arcdps combat data along with a scripting langauge which will enable them RolePlayers to create "Rooms", have a host be the "Dungeon Master", select a "Quest" and start playing with other players. they can assign tasks like "go kill this enemy" and we will use arcdps to track how many enemies they killed to report to DM (dungeon master), or "go to this spot with this item in your inventory" and we will use gw2 api to get items in inventory while mumblelink provides us with the location to track player to emit a successfully completed task event for that player.

having web support will allow others to watch/monitor these live roleplay quests of other players, inside the browser on android or macos.
