### ISSUE TITLE
Forking off `bevy_glfw`

### ISSUE THREAD

**Issue by Friz64** [coderedart/jokolay#42]
Hey there! I see that this repository has previously contained an GLFW backend for `bevy_window`, before being removed in d7bcf60a6d6bd1f91e525a81df927e02140a0455.

I ask for permission to use that old code as a base for an actual `bevy_glfw` crate, where my aim is to improve and maintain it. I am planning to license the fork under _MIT or Apache 2.0_, as per the [Bevy Third Party Plugin Guidelines](https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md#licensing). I will credit your name.

As an aside, my motivation behind this is that I personally find it inconvenient to use winit due to its lack of proper keyboard input handling, as I'm using a non-qwerty keyboard layout, Colemak, which scrambles the key mapping in games, making it very difficult to use without making an effort to remap all keys to their correct locations. GLFW, on the other hand, always assumes a qwerty layout, no matter where the keys are physically located on the keyboard, which is the preferred behaviour in games. There is work underway to fix this in winit, but it's not done yet (https://github.com/rust-windowing/winit/issues/1806).

**Comment by coderedart** [comment]
sure. take whatever you want :) 

Thanks for maintaining the erupt crate btw, It really helped me out when i was learning vulkan and used it in this repo in the past.

**Comment by Friz64** [comment]
I ended up rewriting most of the code (including using custom GLFW bindings), but here it is: https://docs.rs/bevy_glfw/

**Comment by coderedart** [comment]
any particular reason for writing generating new bindings?

**Comment by Friz64** [comment]
Allows more specialized and independent code, [PistonDevelopers/glfw-rs](https://github.com/PistonDevelopers/glfw-rs) has 8 years of historical baggage.
