### ISSUE TITLE
Paths seem to get connected somewhere under the map.

### ISSUE THREAD

**Issue by MvBonin** [coderedart/jokolay#48]
In most maps the paths are cut somewhere and meet underneath it.

![Screenshot from 2023-11-03 18-31-11](https://github.com/coderedart/jokolay/assets/41330432/ce607b21-d2a4-473f-a4a5-7c7054003e42)
![Screenshot from 2023-11-03 18-31-16](https://github.com/coderedart/jokolay/assets/41330432/a6138133-7001-4cf2-a9f8-6450e318c8c7)

**Comment by coderedart** [comment]
I found that weird too. will check the trail mesh generation. could be some sort of bug like starting all trails from [0.0, 0.0, 0.0] coordinate or something like that.

**Comment by coderedart** [comment]
It seems some trails have a node at [0, 0, 0] somewhere in the middle. If you click `JKL` -> mumble info, then you can see your character position on map. These trails should be meeting at [0, 0, 0] most of the time.

 In queensdale, i found these
```
  2023-11-11T20:38:52.932078Z  INFO  found zeroes in tbin, tbin_path: data/tw/blkf/tw_blkf_tt02_03_1_toggletrail.trl, index: 114
    at crates/joko_marker_format/src/manager/live_pack.rs:409

  2023-11-11T20:38:52.933548Z  INFO  found zeroes in tbin, tbin_path: data/tw/fishing/tw_fishing_queensdale_lake.trl, index: 60
    at crates/joko_marker_format/src/manager/live_pack.rs:409

  2023-11-11T20:38:52.934399Z  INFO  found zeroes in tbin, tbin_path: data/tw/fishing/tw_fishing_queensdale_river.trl, index: 70
    at crates/joko_marker_format/src/manager/live_pack.rs:409
```
By disabling the bl key farming and fishing categories, i could verify that all the trails that met at this point disappeared. 

I checked the original tekkit pack by opening `data/tw/blkf/tw_blkf_tto2_o3_1_toggle.trl` and checking the bytes at offset `1376`, where i found 3 floats with zero value.

![image](https://github.com/coderedart/jokolay/assets/24411704/4e1c6809-46f8-48a0-a126-09d779f53e1a)

So, everything is working fine on our side. Need to check if the same issue actually exists for Blish/Taco too. Or maybe they just ignore any node that is [0, 0, 0]? or if they skip a node if its further than x meters in distance from the previous node?

**Comment by coderedart** [comment]
fixed. It seems trails have a special case, where you can "split" a single trail as multiple disjoint paths by adding a zero position. I will make a quick release of v0.2.2, so that someone can verify that this works everywhere.
