### ISSUE TITLE
Compatiblity issue with Tekkit's Workshop in Janthir Wilds?

### ISSUE THREAD

**Issue by couladin** [coderedart/jokolay#53]
Hesitant to post this, as Tekkit's TacO update containing Janthir Wilds is new and they may be ironing out issues, but given the time since there was an update on Jokolay (I'm on 0.2.2), I'm wondering if this may be Jokolay related (e.g. map API boundaries, the sorting issue in Issue #47, etc).

Judging from their Discord, it appears to be working under BlishHUD, but I can't get it to work in Jokolay (EndeavourOS, KDE, X11). Today's version of TW's All-in-One file is 3.6.2. (The webpage says 3.6.1 in the title, but the [download page](https://www.tekkitsworkshop.net/index.php/download) takes to you 3.6.2).

Looking inside the TacO/Zip file I can see JW-related XML (one new and plenty inside existing XML), a bunch of new TRL and image files, and some content in the Markers menu when loaded, but nothing appears onscreen. The markers for all non-JW zones work fine.

- Menu entry example:

![menu](https://github.com/user-attachments/assets/58b4e2fe-925d-4580-8f51-357a7248f9ac)

- Mastery Points sub-menu example:

![mastery_points](https://github.com/user-attachments/assets/7fc68a49-e4f5-432c-8def-f3e5523dab62)

Unfortunately, the Jokolay "Show Logs" window can't be widened (only the 'target|line' edge and height can be adjusted), so the best I can see is:

![show_logs](https://github.com/user-attachments/assets/2f809e98-d75a-4944-88b0-0e99bca6609d)

Those "failed to..." lines suggest a problem making sense of the XML or TRL data? Let me know if there's any data you need from me.

**Comment by coderedart** [comment]
you can find the logfile at `~/.local/share/jokolay/jokolay.log`. It will help with figuring out the issues.

**Comment by couladin** [comment]
Sure thing. Current file attached.

[jokolay.log](https://github.com/user-attachments/files/16825014/jokolay.log)

**Comment by coderedart** [comment]
Its a utf-8 error. tekkit seems to have put it some weird emoji or something in `line 349` of the `tw_exp05_jw.xml` file:
```xml
<MarkerCategory name="tw_jw_janthirsyntri_buildaquagan_spot09" DisplayName="Return to Forager's Hunt�it's time to make a new Mr. Quiggles!" achievementBit="8" />
```

You can see the invalid character in the `DisplayName` attribute right after the text `Forager's Hunt` and before `it's time to`

I will post the error in tekkit's discord, but if you really can't wait, you can just download the zip, fix the error (delete the invalid character) and then import the fixed zip instead.

**Comment by coderedart** [comment]
The Ui update will come tomorrow. And then markers stuff will be made into an addon while fixing the markers menu sorting thing from #47 .  Hopefully, that will let others contribute faster (or make their own addons).

**Comment by couladin** [comment]
That's great news, and thanks for looking and finding it so quickly.

**Comment by MvBonin** [comment]
Hey @coderedart a little follow-up:
Are you still working on the UI update? Can I help you somehow?

**Comment by coderedart** [comment]
Still working on it. I *almost* got it done a few weeks ago, but hit a wall (wayland support and animations) and had to change the design again (Its probably the fifth time this happend?).

I think I have a good enough design now that supports all the constraints (custom user themes, custom widgets (eg: mount radial), lua + wasm plugins, native wayland support etc..). I will just push whatever work I can do today and then tomorrow, make a bunch of issues which people can help with.
